import type { BasisPoints, EntityId, GameSeconds, MoneyCents } from "../contracts/types.js";

export interface CityDefinition { id: EntityId; name: string; level: string; x: number; y: number; longitude: number; latitude: number; provinceCode: string; regionId: EntityId; modes: string[]; industryTags: string[]; active: boolean; }
export interface RegionDefinition { id: EntityId; name: string; centerLongitude: number; centerLatitude: number; status: "active" | "gateway" | "locked"; requiredReputationBasisPoints: BasisPoints; active: boolean; }
export type MapDetailLevel = "national" | "province" | "county" | "local";
export interface MapZoomLevelDefinition { id: MapDetailLevel; label: string; minZoom: number; }
export interface NationalMapConfig { id: EntityId; assetId: EntityId; minLongitude: number; maxLongitude: number; minLatitude: number; maxLatitude: number; initialCenterLongitude: number; initialCenterLatitude: number; defaultZoom: number; minZoom: number; maxZoom: number; zoomLevels: MapZoomLevelDefinition[]; }
export type MapNodeKind = "national_hub" | "province_hub" | "prefecture_city" | "county_city" | "town" | "logistics_park" | "warehouse" | "fuel_station" | "toll_station" | "cargo_source";
export interface MapNodeDefinition { id: EntityId; name: string; kind: MapNodeKind; mapX?: number; mapY?: number; longitude?: number; latitude?: number; regionId: EntityId; provinceCode: string; parentId: EntityId | null; cityId: EntityId | null; minZoom: number; contentPackId: EntityId; active: boolean; }
export type MapRoadClass = "expressway" | "national" | "provincial" | "county" | "local";
export interface GeoCoordinate { longitude: number; latitude: number; }
export interface MapRoadSegmentDefinition { id: EntityId; name: string; roadClass: MapRoadClass; fromNodeId: EntityId; toNodeId: EntityId; geometry: GeoCoordinate[]; routeIds: EntityId[]; minZoom: number; contentPackId: EntityId; active: boolean; }
export interface RoadDefinition { id: EntityId; from: EntityId; to: EntityId; mode: "road"; distanceMeters: number; baseTravelSeconds: number; tollCents: MoneyCents; active: boolean; }
export interface CargoDefinition { id: EntityId; name: string; temperature: string; fragility: number; active: boolean; }
export interface VehicleModelDefinition { id: EntityId; name: string; category: string; mode: "road_freight"; capacityKg: number; capacityLiters: number; purchasePriceCents: MoneyCents; baseConsumption: number; capabilities: string[]; requiredReputationBasisPoints: BasisPoints; dealerAvailable: boolean; assetId: string; active: boolean; }
export interface MarketEventDefinition { id: EntityId; headline: string; cityId: EntityId; cargoId: EntityId; demandModifierBasisPoints: BasisPoints; durationSeconds: GameSeconds; active: boolean; }
export interface CustomerContractDefinition { id: EntityId; customerName: string; title: string; originCityId: EntityId; destinationCityId: EntityId; cargoId: EntityId; requiredReputationBasisPoints: BasisPoints; signingFeeCents: MoneyCents; rewardBonusBasisPoints: BasisPoints; milestoneOrders: number; active: boolean; }
export type OrderStatus = "available" | "accepted" | "in_transit" | "delivered" | "failed" | "cancelled";
export interface OrderTemplate { id: EntityId; cargoId: EntityId; originCityId: EntityId; destinationCityId: EntityId; weightKg: number; volumeLiters: number; rewardCents: MoneyCents; availableAt: GameSeconds; deadlineAt: GameSeconds; status: OrderStatus; }
export interface ContentBundle { mapConfig: NationalMapConfig; regions: RegionDefinition[]; mapNodes: MapNodeDefinition[]; mapRoadSegments: MapRoadSegmentDefinition[]; cities: CityDefinition[]; routes: RoadDefinition[]; cargoTypes: CargoDefinition[]; vehicleModels: VehicleModelDefinition[]; orderTemplates: OrderTemplate[]; marketEvents: MarketEventDefinition[]; customerContracts: CustomerContractDefinition[]; }
export interface MarketOrder extends OrderTemplate { status: OrderStatus; }
export interface TripState { routeId: EntityId; routeIds: EntityId[]; routeIndex: number; finalCityId: EntityId; purpose: "delivery" | "reposition"; fromCityId: EntityId; toCityId: EntityId; startedAt: GameSeconds; arrivesAt: GameSeconds; distanceMeters: number; orderIds: EntityId[]; projectedCostCents: MoneyCents; }
export interface VehicleUnitState { id: EntityId; modelId: EntityId; currentCityId: EntityId; status: "idle" | "loading" | "in_transit"; conditionBasisPoints: BasisPoints; mileageMeters: number; loadedDistanceMeters: number; emptyDistanceMeters: number; assignedOrderIds: EntityId[]; trip: TripState | null; acquisitionSource: "starter" | "dealer" | "used_market"; purchasePriceCents: MoneyCents; loanBalanceCents: MoneyCents; lifetimeRevenueCents: MoneyCents; lifetimeCostCents: MoneyCents; }
export interface CompanyState { id: EntityId; name: string; cashCents: MoneyCents; debtCents: MoneyCents; reputationBasisPoints: BasisPoints; deliveredOrders: number; onTimeOrders: number; totalRevenueCents: MoneyCents; totalCostCents: MoneyCents; headquartersCityId: EntityId; parkingCapacity: number; }
export interface GameEvent { id: EntityId; type: string; occurredAt: GameSeconds; message: string; amountCents?: MoneyCents; }
export interface MarketState { periodIndex: number; activeEventId: EntityId | null; startedAt: GameSeconds; endsAt: GameSeconds; }
export interface UsedVehicleOffer { id: EntityId; modelId: EntityId; priceCents: MoneyCents; conditionBasisPoints: BasisPoints; mileageMeters: number; expiresAt: GameSeconds; }
export interface VehicleMarketState { offerDay: number; lastFinanceDay: number; usedOffers: UsedVehicleOffer[]; nextOfferSerial: number; nextVehicleSerial: number; }
export interface CompanyContractState { definitionId: EntityId; signedAt: GameSeconds; completedOrders: number; earnedBonusCents: MoneyCents; }
export interface GameState { saveVersion: number; gameVersion: string; createdAt: string; updatedAt: string; contentPacks: Array<{ id: string; version: string }>; featureFlags: Record<string, boolean>; clock: { now: GameSeconds; speed: number; paused: boolean }; company: CompanyState; vehicleUnits: VehicleUnitState[]; orders: MarketOrder[]; activeRoutes: EntityId[]; eventLog: GameEvent[]; market: MarketState; vehicleMarket: VehicleMarketState; customerContracts: CompanyContractState[]; randomSeed: number; nextOrderSerial: number; nextEventSerial: number; migrationHistory: string[]; }
export type EngineCommand = { type: "AcceptOrder"; orderId: EntityId } | { type: "AssignTransportUnit"; orderId: EntityId; transportUnitId: EntityId } | { type: "UnassignTransportUnit"; orderId: EntityId; transportUnitId: EntityId } | { type: "StartTrip"; transportUnitId: EntityId } | { type: "RepositionVehicle"; transportUnitId: EntityId; destinationCityId: EntityId } | { type: "SignCustomerContract"; contractId: EntityId } | { type: "AdvanceTime"; elapsedGameSeconds: GameSeconds } | { type: "SetClock"; speed: number; paused: boolean } | { type: "PurchaseNewVehicle"; modelId: EntityId } | { type: "PurchaseUsedVehicle"; offerId: EntityId } | { type: "SellVehicle"; transportUnitId: EntityId } | { type: "ExpandParking" };
export interface CommandResult { ok: boolean; errorCode?: string; events: GameEvent[]; }
